;************************************************************************
;*									*
;*		逆ＭＭＬ変換情報のあるアドレス				*
;*									*
;************************************************************************
UC_DATA_ADDRESS:
	DW	OFFSET UC_D00	;コマンド00h
	DW	OFFSET UC_D01
	DW	OFFSET UC_D02
	DW	OFFSET UC_D03
	DW	OFFSET UC_D04
	DW	OFFSET UC_D05
	DW	OFFSET UC_D06
	DW	OFFSET UC_D07
	DW	OFFSET UC_D08
	DW	OFFSET UC_D09
	DW	OFFSET UC_D0A
	DW	OFFSET UC_D0B
	DW	OFFSET UC_D0C
	DW	OFFSET UC_D0D
	DW	OFFSET UC_D0E
	DW	OFFSET UC_D0F
	DW	OFFSET UC_D10
	DW	OFFSET UC_D11
	DW	OFFSET UC_D12
	DW	OFFSET UC_D13
	DW	OFFSET UC_D14
	DW	OFFSET UC_D15
	DW	OFFSET UC_D16
	DW	OFFSET UC_D17
	DW	OFFSET UC_D18
	DW	OFFSET UC_D19
	DW	OFFSET UC_D1A
	DW	OFFSET UC_D1B
	DW	OFFSET UC_D1C
	DW	OFFSET UC_D1D
	DW	OFFSET UC_D1E
	DW	OFFSET UC_D1F
	DW	OFFSET UC_D20
	DW	OFFSET UC_D21
	DW	OFFSET UC_D22
	DW	OFFSET UC_D23
	DW	OFFSET UC_D24
	DW	OFFSET UC_D25
	DW	OFFSET UC_D26
	DW	OFFSET UC_D27
	DW	OFFSET UC_D28
	DW	OFFSET UC_D29
	DW	OFFSET UC_D2A
	DW	OFFSET UC_D2B
	DW	OFFSET UC_D2C
	DW	OFFSET UC_D2D
	DW	OFFSET UC_D2E
	DW	OFFSET UC_D2F
	DW	OFFSET UC_D30
	DW	OFFSET UC_D31
	DW	OFFSET UC_D32
	DW	OFFSET UC_D33
	DW	OFFSET UC_D34
	DW	OFFSET UC_D35
	DW	OFFSET UC_D36
	DW	OFFSET UC_D37
	DW	OFFSET UC_D38
	DW	OFFSET UC_D39
	DW	OFFSET UC_D3A
	DW	OFFSET UC_D3B
	DW	OFFSET UC_D3C
	DW	OFFSET UC_D3D
	DW	OFFSET UC_D3E
	DW	OFFSET UC_D3F
	DW	OFFSET UC_D40
	DW	OFFSET UC_D41
	DW	OFFSET UC_D42
	DW	OFFSET UC_D43
	DW	OFFSET UC_D44
	DW	OFFSET UC_D45
	DW	OFFSET UC_D46
	DW	OFFSET UC_D47
	DW	OFFSET UC_D48
	DW	OFFSET UC_D49
	DW	OFFSET UC_D4A
	DW	OFFSET UC_D4B
	DW	OFFSET UC_D4C
	DW	OFFSET UC_D4D
	DW	OFFSET UC_D4E
	DW	OFFSET UC_D4F
	DW	OFFSET UC_D50
	DW	OFFSET UC_D51
	DW	OFFSET UC_D52
	DW	OFFSET UC_D53
	DW	OFFSET UC_D54
	DW	OFFSET UC_D55
	DW	OFFSET UC_D56
	DW	OFFSET UC_D57
	DW	OFFSET UC_D58
	DW	OFFSET UC_D59
	DW	OFFSET UC_D5A
	DW	OFFSET UC_D5B
	DW	OFFSET UC_D5C
	DW	OFFSET UC_D5D
	DW	OFFSET UC_D5E
	DW	OFFSET UC_D5F
	DW	OFFSET UC_D60
	DW	OFFSET UC_D61
	DW	OFFSET UC_D62
	DW	OFFSET UC_D63
	DW	OFFSET UC_D64
	DW	OFFSET UC_D65
	DW	OFFSET UC_D66
	DW	OFFSET UC_D67
	DW	OFFSET UC_D68
	DW	OFFSET UC_D69
	DW	OFFSET UC_D6A
	DW	OFFSET UC_D6B
	DW	OFFSET UC_D6C
	DW	OFFSET UC_D6D
	DW	OFFSET UC_D6E
	DW	OFFSET UC_D6F
	DW	OFFSET UC_D70
	DW	OFFSET UC_D71
	DW	OFFSET UC_D72
	DW	OFFSET UC_D73
	DW	OFFSET UC_D74
	DW	OFFSET UC_D75
	DW	OFFSET UC_D76
	DW	OFFSET UC_D77
	DW	OFFSET UC_D78
	DW	OFFSET UC_D79
	DW	OFFSET UC_D7A
	DW	OFFSET UC_D7B
	DW	OFFSET UC_D7C
	DW	OFFSET UC_D7D
	DW	OFFSET UC_D7E
	DW	OFFSET UC_D7F
	DW	OFFSET UC_D80
	DW	OFFSET UC_D81
	DW	OFFSET UC_D82
	DW	OFFSET UC_D83
	DW	OFFSET UC_D84
	DW	OFFSET UC_D85
	DW	OFFSET UC_D86
	DW	OFFSET UC_D87
	DW	OFFSET UC_D88
	DW	OFFSET UC_D89
	DW	OFFSET UC_D8A
	DW	OFFSET UC_D8B
	DW	OFFSET UC_D8C
	DW	OFFSET UC_D8D
	DW	OFFSET UC_D8E
	DW	OFFSET UC_D8F
	DW	OFFSET UC_D90
	DW	OFFSET UC_D91
	DW	OFFSET UC_D92
	DW	OFFSET UC_D93
	DW	OFFSET UC_D94
	DW	OFFSET UC_D95
	DW	OFFSET UC_D96
	DW	OFFSET UC_D97
	DW	OFFSET UC_D98
	DW	OFFSET UC_D99
	DW	OFFSET UC_D9A
	DW	OFFSET UC_D9B
	DW	OFFSET UC_D9C
	DW	OFFSET UC_D9D
	DW	OFFSET UC_D9E
	DW	OFFSET UC_D9F
	DW	OFFSET UC_DA0
	DW	OFFSET UC_DA1
	DW	OFFSET UC_DA2
	DW	OFFSET UC_DA3
	DW	OFFSET UC_DA4
	DW	OFFSET UC_DA5
	DW	OFFSET UC_DA6
	DW	OFFSET UC_DA7
	DW	OFFSET UC_DA8
	DW	OFFSET UC_DA9
	DW	OFFSET UC_DAA
	DW	OFFSET UC_DAB
	DW	OFFSET UC_DAC
	DW	OFFSET UC_DAD
	DW	OFFSET UC_DAE
	DW	OFFSET UC_DAF
	DW	OFFSET UC_DB0
	DW	OFFSET UC_DB1
	DW	OFFSET UC_DB2
	DW	OFFSET UC_DB3
	DW	OFFSET UC_DB4
	DW	OFFSET UC_DB5
	DW	OFFSET UC_DB6
	DW	OFFSET UC_DB7
	DW	OFFSET UC_DB8
	DW	OFFSET UC_DB9
	DW	OFFSET UC_DBA
	DW	OFFSET UC_DBB
	DW	OFFSET UC_DBC
	DW	OFFSET UC_DBD
	DW	OFFSET UC_DBE
	DW	OFFSET UC_DBF
	DW	OFFSET UC_DC0
	DW	OFFSET UC_DC1
	DW	OFFSET UC_DC2
	DW	OFFSET UC_DC3
	DW	OFFSET UC_DC4
	DW	OFFSET UC_DC5
	DW	OFFSET UC_DC6
	DW	OFFSET UC_DC7
	DW	OFFSET UC_DC8
	DW	OFFSET UC_DC9
	DW	OFFSET UC_DCA
	DW	OFFSET UC_DCB
	DW	OFFSET UC_DCC
	DW	OFFSET UC_DCD
	DW	OFFSET UC_DCE
	DW	OFFSET UC_DCF
	DW	OFFSET UC_DD0
	DW	OFFSET UC_DD1
	DW	OFFSET UC_DD2
	DW	OFFSET UC_DD3
	DW	OFFSET UC_DD4
	DW	OFFSET UC_DD5
	DW	OFFSET UC_DD6
	DW	OFFSET UC_DD7
	DW	OFFSET UC_DD8
	DW	OFFSET UC_DD9
	DW	OFFSET UC_DDA
	DW	OFFSET UC_DDB
	DW	OFFSET UC_DDC
	DW	OFFSET UC_DDD
	DW	OFFSET UC_DDE
	DW	OFFSET UC_DDF
	DW	OFFSET UC_DE0
	DW	OFFSET UC_DE1
	DW	OFFSET UC_DE2
	DW	OFFSET UC_DE3
	DW	OFFSET UC_DE4
	DW	OFFSET UC_DE5
	DW	OFFSET UC_DE6
	DW	OFFSET UC_DE7
	DW	OFFSET UC_DE8
	DW	OFFSET UC_DE9
	DW	OFFSET UC_DEA
	DW	OFFSET UC_DEB
	DW	OFFSET UC_DEC
	DW	OFFSET UC_DED
	DW	OFFSET UC_DEE
	DW	OFFSET UC_DEF
	DW	OFFSET UC_DF0
	DW	OFFSET UC_DF1
	DW	OFFSET UC_DF2
	DW	OFFSET UC_DF3
	DW	OFFSET UC_DF4
	DW	OFFSET UC_DF5
	DW	OFFSET UC_DF6
	DW	OFFSET UC_DF7
	DW	OFFSET UC_DF8
	DW	OFFSET UC_DF9
	DW	OFFSET UC_DFA
	DW	OFFSET UC_DFB
	DW	OFFSET UC_DFC
	DW	OFFSET UC_DFD
	DW	OFFSET UC_DFE
	DW	OFFSET UC_DFF
;************************************************************************
;*									*
;*		逆ＭＭＬ情報						*
;*									*
;************************************************************************
;*	（最初に変換アドレス＋１されている。）				*
;*	00h	変換終了						*
;*	10h	符号無しＢｙｔｅ変換	アドレス＋１			*
;*	11h	符号有りＢｙｔｅ変換	アドレス＋１			*
;*	12h	符号無しＷｏｒｄ変換	アドレス＋１			*
;*	13h	符号有りＷｏｒｄ変換	アドレス＋１			*
;*	20h	文字列出力　'$'まで出力する。				*
;*	21h	次の発音はタイで繋がれるか検索				*
;*	24h	次のコードの出力					*
;*	80h	パート終了						*
;*	F0h	アドレス＋１	（未解析コマンドの引き数）		*
;*	FFh	次に示すアドレスをコールする				*
;************************************************************************
UC_D00	DB	' c1$',21h,00h		;音程
UC_D01	DB	' c2$',21h,00h
UC_D02	DB	' c4$',21h,00h
UC_D03	DB	' c8$',21h,00h
UC_D04	DB	' c16$',21h,00h
UC_D05	DB	' c32$',21h,00h
UC_D06	DB	' c64$',21h,00h
UC_D07	DB	' c6$',21h,00h
UC_D08	DB	' c12$',21h,00h
UC_D09	DB	' c24$',21h,00h
UC_D0A	DB	' c48$',21h,00h
UC_D0B	DB	' c+1$',21h,00h
UC_D0C	DB	' c+2$',21h,00h
UC_D0D	DB	' c+4$',21h,00h
UC_D0E	DB	' c+8$',21h,00h
UC_D0F	DB	' c+16$',21h,00h
UC_D10	DB	' c+32$',21h,00h
UC_D11	DB	' c+64$',21h,00h
UC_D12	DB	' c+6$',21h,00h
UC_D13	DB	' c+12$',21h,00h
UC_D14	DB	' c+24$',21h,00h
UC_D15	DB	' c+48$',21h,00h
UC_D16	DB	' d1$',21h,00h
UC_D17	DB	' d2$',21h,00h
UC_D18	DB	' d4$',21h,00h
UC_D19	DB	' d8$',21h,00h
UC_D1A	DB	' d16$',21h,00h
UC_D1B	DB	' d32$',21h,00h
UC_D1C	DB	' d64$',21h,00h
UC_D1D	DB	' d6$',21h,00h
UC_D1E	DB	' d12$',21h,00h
UC_D1F	DB	' d24$',21h,00h
UC_D20	DB	' d48$',21h,00h
UC_D21	DB	' d+1$',21h,00h
UC_D22	DB	' d+2$',21h,00h
UC_D23	DB	' d+4$',21h,00h
UC_D24	DB	' d+8$',21h,00h
UC_D25	DB	' d+16$',21h,00h
UC_D26	DB	' d+32$',21h,00h
UC_D27	DB	' d+64$',21h,00h
UC_D28	DB	' d+6$',21h,00h
UC_D29	DB	' d+12$',21h,00h
UC_D2A	DB	' d+24$',21h,00h
UC_D2B	DB	' d+48$',21h,00h
UC_D2C	DB	' e1$',21h,00h
UC_D2D	DB	' e2$',21h,00h
UC_D2E	DB	' e4$',21h,00h
UC_D2F	DB	' e8$',21h,00h
UC_D30	DB	' e16$',21h,00h
UC_D31	DB	' e32$',21h,00h
UC_D32	DB	' e64$',21h,00h
UC_D33	DB	' e6$',21h,00h
UC_D34	DB	' e12$',21h,00h
UC_D35	DB	' e24$',21h,00h
UC_D36	DB	' e48$',21h,00h
UC_D37	DB	' f1$',21h,00h
UC_D38	DB	' f2$',21h,00h
UC_D39	DB	' f4$',21h,00h
UC_D3A	DB	' f8$',21h,00h
UC_D3B	DB	' f16$',21h,00h
UC_D3C	DB	' f32$',21h,00h
UC_D3D	DB	' f64$',21h,00h
UC_D3E	DB	' f6$',21h,00h
UC_D3F	DB	' f12$',21h,00h
UC_D40	DB	' f24$',21h,00h
UC_D41	DB	' f48$',21h,00h
UC_D42	DB	' f+1$',21h,00h
UC_D43	DB	' f+2$',21h,00h
UC_D44	DB	' f+4$',21h,00h
UC_D45	DB	' f+8$',21h,00h
UC_D46	DB	' f+16$',21h,00h
UC_D47	DB	' f+32$',21h,00h
UC_D48	DB	' f+64$',21h,00h
UC_D49	DB	' f+6$',21h,00h
UC_D4A	DB	' f+12$',21h,00h
UC_D4B	DB	' f+24$',21h,00h
UC_D4C	DB	' f+48$',21h,00h
UC_D4D	DB	' g1$',21h,00h
UC_D4E	DB	' g2$',21h,00h
UC_D4F	DB	' g4$',21h,00h
UC_D50	DB	' g8$',21h,00h
UC_D51	DB	' g16$',21h,00h
UC_D52	DB	' g32$',21h,00h
UC_D53	DB	' g64$',21h,00h
UC_D54	DB	' g6$',21h,00h
UC_D55	DB	' g12$',21h,00h
UC_D56	DB	' g24$',21h,00h
UC_D57	DB	' g48$',21h,00h
UC_D58	DB	' g+1$',21h,00h
UC_D59	DB	' g+2$',21h,00h
UC_D5A	DB	' g+4$',21h,00h
UC_D5B	DB	' g+8$',21h,00h
UC_D5C	DB	' g+16$',21h,00h
UC_D5D	DB	' g+32$',21h,00h
UC_D5E	DB	' g+64$',21h,00h
UC_D5F	DB	' g+6$',21h,00h
UC_D60	DB	' g+12$',21h,00h
UC_D61	DB	' g+24$',21h,00h
UC_D62	DB	' g+48$',21h,00h
UC_D63	DB	' a1$',21h,00h
UC_D64	DB	' a2$',21h,00h
UC_D65	DB	' a4$',21h,00h
UC_D66	DB	' a8$',21h,00h
UC_D67	DB	' a16$',21h,00h
UC_D68	DB	' a32$',21h,00h
UC_D69	DB	' a64$',21h,00h
UC_D6A	DB	' a6$',21h,00h
UC_D6B	DB	' a12$',21h,00h
UC_D6C	DB	' a24$',21h,00h
UC_D6D	DB	' a48$',21h,00h
UC_D6E	DB	' a+1$',21h,00h
UC_D6F	DB	' a+2$',21h,00h
UC_D70	DB	' a+4$',21h,00h
UC_D71	DB	' a+8$',21h,00h
UC_D72	DB	' a+16$',21h,00h
UC_D73	DB	' a+32$',21h,00h
UC_D74	DB	' a+64$',21h,00h
UC_D75	DB	' a+6$',21h,00h
UC_D76	DB	' a+12$',21h,00h
UC_D77	DB	' a+24$',21h,00h
UC_D78	DB	' a+48$',21h,00h
UC_D79	DB	' b1$',21h,00h
UC_D7A	DB	' b2$',21h,00h
UC_D7B	DB	' b4$',21h,00h
UC_D7C	DB	' b8$',21h,00h
UC_D7D	DB	' b16$',21h,00h
UC_D7E	DB	' b32$',21h,00h
UC_D7F	DB	' b64$',21h,00h
UC_D80	DB	' b6$',21h,00h
UC_D81	DB	' b12$',21h,00h
UC_D82	DB	' b24$',21h,00h
UC_D83	DB	' b48$',21h,00h
UC_D84	DB	' r1$',21h,00h		;タイで繋がれる
UC_D85	DB	' r2$',21h,00h		;同上	
UC_D86	DB	' r4$',21h,00h		;同上	
UC_D87	DB	' r8$',21h,00h		;同上	
UC_D88	DB	' r16$',21h,00h		;同上	
UC_D89	DB	' r32$',21h,00h		;同上	
UC_D8A	DB	' r64$',21h,00h		;同上	
UC_D8B	DB	' r6$',21h,00h		;同上	
UC_D8C	DB	' r12$',21h,00h		;同上	
UC_D8D	DB	' r24$',21h,00h		;同上	
UC_D8E	DB	' r48$',21h,00h		;同上	
UC_D8F	DB	' r1$',21h,00h
UC_D90	DB	' r2$',21h,00h
UC_D91	DB	' r4$',21h,00h
UC_D92	DB	' r8$',21h,00h
UC_D93	DB	' r16$',21h,00h
UC_D94	DB	' r32$',21h,00h
UC_D95	DB	' r64$',21h,00h
UC_D96	DB	' r6$',21h,00h
UC_D97	DB	' r12$',21h,00h
UC_D98	DB	' r24$',21h,00h
UC_D99	DB	' r48$',21h,00h
UC_D9A	DB	' /*9A*/$',00h
UC_D9B	DB	' /*9B*/$',00h
UC_D9C	DB	' /*9C*/$',00h
UC_D9D	DB	' /*9D*/$',00h
UC_D9E	DB	' /*9E*/$',00h
UC_D9F	DB	' /*9F*/$',00h
UC_DA0	DB	80h,00h			;終了
UC_DA1	DB	24h,24h,0FFH		;音色	'$'の出力
	DW	OFFSET UC_VOICE_OUTPUT	;	マクロ番号出力
	DB	00h			;	使用マクロ記憶
UC_DA2	DB	' /*A2,$',0ffH		;リリースタイム
	DW	OFFSET UC_DELAY
	DB	' */$',00h
UC_DA3	DB	' v$',0FFh		;音量（ただしリニア）
	DW	OFFSET UC_Volume	
	DB	00h			
UC_DA4	DB	' /*A4,$',10h,' ,$', 11h,' */$',00h	;ポルタメント
;UC_DA4	DB	' y5,$',10h,' y84,$',10h,00h
UC_DA5	DB	' o$',10h,00h		;オクターブ
UC_DA6	DB	' >$',00h		;オクターブアップ
UC_DA7	DB	' <$',00h		;オクターブダウン
UC_DA8	DB	' E$',0FFh		;expression
	DW	OFFSET UC_SAVE_E	
	DB	10h,00h
UC_DA9	DB	' E$',0FFh		;expression move
	DW	OFFSET UC_LOAD_ES
	DB	' UE1,0,%$',10h,' ,$',0FFh
	DW	OFFSET UC_LOAD_E
	DB	00h
UC_DAA	DB	' p$',0FFh		;panpot
	DW	OFFSET UC_SAVE_P
	DB	10h,00h
UC_DAB	DB	' p$',0FFh		;panpot move
	DW	OFFSET UC_LOAD_PS
	DB	' UP1,0,%$',10h,' ,$',0FFh
	DW	OFFSET UC_LOAD_P
	DB	00h
UC_DAC	DB	' /*AC,$',010h,' */$',00h	;不明
UC_DAD	DB	' /*AD(AL),$',010h,' */$',00h	;不明
UC_DAE	DB	' /*AE(DL),$',010h,' */$',00h	;不明
UC_DAF	DB	' /*AF(SL),$',010h,' */$',00h	;不明
UC_DB0	DB	' /*B0*/$',00h
UC_DB1	DB	' /*B1(SR),$',010h,' */$',00h	;不明
UC_DB2	DB	' /*B2(RR),$',010h,' */$',00h	;不明
UC_DB3	DB	' /*B3*/$',00h
UC_DB4	DB	' /*B4,$',010h,' ,$',010h,' ,$',010h,' */$',00h	;
UC_DB5	DB	' /*B5,$',010h,' */$',00h			;
UC_DB6	DB	' /*B6*/$',00h					;
UC_DB7	DB	' /*B7*/$',00h
UC_DB8	DB	' /*B8,$',010h,' ,$',010h,' ,$',010h,' */$',00h	;
UC_DB9	DB	' /*B9,$',010h,' */$',00h			;
UC_DBA	DB	' /*BA*/$',00h					;
UC_DBB	DB	' /*BB*/$',00h
UC_DBC	DB	' /*BC,$',010h,' ,$',010h,' */$',00h		;
UC_DBD	DB	' /*BD,$',010h,' */$',00h			;
UC_DBE	DB	' /*BE*/$',00h					;
UC_DBF	DB	' /*BF*/$',00h
UC_DC0	DB	' /*C0*/$',00h
UC_DC1	DB	' /*C1*/$',00h
UC_DC2	DB	' y91,80$',00h		;Reverb on
UC_DC3	DB	' y91,0 $',00h		;Reverb off
UC_DC4	DB	' /*C4*/$',00h
UC_DC5	DB	' /*C5*/$',00h
UC_DC6	DB	' /*C6(Mon)*/$',00h	;modulation on
UC_DC7	DB	' /*C7(Moff)*/$',00h	;modulation off
UC_DC8	DB	' [$',00h		;Loop start
UC_DC9	DB	' ]$',10h,00h		;Loop end
UC_DCA	DB	' /*CA*/$',00h
UC_DCB	DB	' /*CB*/$',00h
UC_DCC	DB	' P$'			;スラー開始
UC_DCD	DB	' X$'			;スラー終了
UC_DCE	DB	' /*CE*/$',00h
UC_DCF	DB	' /*CF*/$',00h
UC_DD0	DB	' /*D0*/$',00h
UC_DD1	DB	' /*D1*/$',00h
UC_DD2	DB	' /*D2*/$',00h
UC_DD3	DB	' /*D3*/$',00h
UC_DD4	DB	' /*D4*/$',00h
UC_DD5	DB	' /*D5*/$',00h
UC_DD6	DB	' /*D6*/$',00h
UC_DD7	DB	' /*D7*/$',00h
UC_DD8	DB	' BS$',0FFh		;ディチューン
	DW	offset UC_Detune
	DB	00h
UC_DD9	DB	' /*D9*/$',00h
UC_DDA	DB	' /*DA,$',010h,' */$',00h	;不明
UC_DDB	DB	' /*DB*/$',00h
UC_DDC	DB	' /*DC*/$',00h
UC_DDD	DB	' /*DD*/$',00h
UC_DDE	DB	' /*DE,$',010h,' ,$',010h,' */$',00h	;不明
UC_DDF	DB	' /*DF*/$',00h
UC_DE0	DB	' /*E0*/$',00h
UC_DE1	DB	' /*E1*/$',00h
UC_DE2	DB	' /*E2*/$',00h
UC_DE3	DB	' /*E3*/$',00h
UC_DE4	DB	' /*E4*/$',00h
UC_DE5	DB	' /*E5*/$',00h
UC_DE6	DB	' /*E6,$',010h,' ,$',010h,' */$',00h	
UC_DE7	DB	' /*E7*/$',00h
UC_DE8	DB	' /*E8*/$',00h
UC_DE9	DB	' /*E9*/$',00h
UC_DEA	DB	' /*EA*/$',00h
UC_DEB	DB	' /*EB*/$',00h
UC_DEC	DB	' /*EC*/$',00h
UC_DED	DB	' /*ED*/$',00h
UC_DEE	DB	' /*EE*/$',00h
UC_DEF	DB	' /*EF*/$',00h
UC_DF0	DB	' c%$',10h,21h,00h
UC_DF1	DB	' c+%$',10h,21h,00h
UC_DF2	DB	' d%$',10h,21h,00h
UC_DF3	DB	' d+%$',10h,21h,00h
UC_DF4	DB	' e%$',10h,21h,00h
UC_DF5	DB	' f%$',10h,21h,00h
UC_DF6	DB	' f+%$',10h,21h,00h
UC_DF7	DB	' g%$',10h,21h,00h
UC_DF8	DB	' g+%$',10h,21h,00h
UC_DF9	DB	' a%$',10h,21h,00h
UC_DFA	DB	' a+%$',10h,21h,00h
UC_DFB	DB	' b%$',10h,21h,00h
UC_DFC	DB	' r%$',10h,21h,00h	;タイで繋がれる。
UC_DFD	DB	' r%$',10h,21h,00h
UC_DFE	DB	0FFh
	DW	OFFSET UCDFF_LSTART
	DB	00h
UC_DFF	DB	' /*FF*/$',00h		;不明


;===============================================================
;	0xFE系コマンドの処理
;===============================================================
;---------------------------------------
;	開始
;---------------------------------------
UCDFF_LSTART:
	MOV	AL,ES:[BX]	;データ読み込み
	INC	BX		;
	jmp	UCDFF_L00	
;---------------------------------------
;	0x00	テンポ
;---------------------------------------
UCDFF_M00	DB	't$'
UCDFF_L00:
	CMP	AL,00h		;テンポ命令
	JZ	UCDFF_L01_1
	JMP	UCDFF_L02	;
UCDFF_L01_1:
	MOV	DX,OFFSET UCDFF_M00
	MOV	AH,09H		;
	INT	21H		;
	MOV	AX,ES:[BX]	;AX←データ（WORD）
	INC	BX		;
	INC	BX		;
	PUSH	CX		;
	XOR	DX,DX		;DX,AX←Ax
	MOV	CX,218		;
	DIV	CX		;ax←dx,ax÷218
	POP	CX		;
	CALL	HEX2ASC16	;数値変換
	MOV	AH,09H		;
	INT	21H		;そしてそれを表示
	RET
;---------------------------------------
;	0x02	？
;---------------------------------------
UCDFF_L02:
;	CMP	AL,02h		;不明
;	JZ	UCDFF_L02_1	;
	JMP	UCDFF_L04	;
UCDFF_L02_1:
;	INC	BX		;
;	INC	BX		;
;	RET			;
;---------------------------------------
;	0x04	パーカッション
;---------------------------------------
UCDFF_M04	DB	'RT EX x41,x10,x42,x12,{x40,x1$'
UCDFF_M04_D0	DB	'1$'
		DB	'2$'
		DB	'3$'
		DB	'4$'
		DB	'5$'
		DB	'6$'
		DB	'7$'
		DB	'8$'
		DB	'9$'
		DB	'0$'
		DB	'a$'
		DB	'b$'
		DB	'c$'
		DB	'd$'
		DB	'e$'
		DB	'f$'
UCDFF_M04_2	DB	',x15,1},xF7H0,3@0$'
UCDFF_L04:
	CMP	AL,04h		;リズムパートだよ。
	JZ	UCDFF_L04_1
	JMP	UCDFF_L06	;
UCDFF_L04_1:
	MOV	DX,OFFSET UCDFF_M04
	MOV	AH,09H		;
	INT	21H		;
	XOR	DX,DX		;
	MOV	DL,CH		;
	AND	DL,0FH		;
	SHL	DX,1
	ADD	DX,OFFSET UCDFF_M04_D0
	MOV	AH,09H		;
	INT	21H		;
	MOV	DX,OFFSET UCDFF_M04_2
	MOV	AH,09H		;
	INT	21H		;
	RET
;---------------------------------------
;	0x06	終了
;---------------------------------------
UCDFF_M06_1	DB	']2/*L*/$'
UCDFF_M06_bx	Dw	0
UCDFF_L06:
	CMP	AL,06h		;データ終了
	JZ	UCDFF_L06_1	;
	JMP	UCDFF_L07	;
UCDFF_L06_1:			;
	mov	ax,bx		;
	mov	cs:[UCDFF_M06_bx],ax
	MOV	AX,ES:[BX]	;
	TEST	AX,AX		;
	JNZ	UCDFF_L06_4	;
	JMP	UCDFF_L06_3	;
UCDFF_L06_4:			
	ADD	BX,AX		;BX←ループ先アドレス
	MOV	AX,CS:[UCMOLS_LOOP_ADDRESS]	;検索したループ先アドレス
;	CMP	AX,BX		;同一
;	JZ	UCDFF_L06_2	;
;	RET			;でないならば、ジャンプ
UCDFF_L06_2:			;
	TEST	AX,AX		;
	JZ	UCDFF_L06_3	;
	MOV	DX,OFFSET UCDFF_M06_1
	MOV	AH,09H		;
	INT	21H		;

	cmp	byte ptr cs:[UCMOLS_LOOP_flag2],01h	;
	jnz	UCDFF_L06_3
	mov	byte ptr cs:[UCMOLS_LOOP_flag2],00h	;
	mov	ax,cs:[UCDFF_M06_bx]
	mov	bx,ax
	add	bx,2
	ret

UCDFF_L06_3:			;
	POP	DX		;ダミー
	XCHG	BX,DX		;
	MOV	BX,SP		;
	MOV	AX,OFFSET UCMO_LQQ
	MOV	SS:[BX],AX	;
	XCHG	BX,DX		;
	RET			;
;---------------------------------------
;	0x07	条件ジャンプ
;---------------------------------------
UCDFF_M07_1	DB	'/*FE,7,$'
UCDFF_M07_2	DB	'*/:$'
UCDFF_L07:
	CMP	AL,07h		;データ終了
	JZ	UCDFF_L07_1	;
	JMP	UCDFF_L09	;
UCDFF_L07_1:
	MOV	DX,OFFSET UCDFF_M07_1
	MOV	AH,09H		;
	INT	21H		;

	mov	ah,es:[bx]
	inc	bx		;
	call	hex2asc8
	MOV	AH,09H		;
	INT	21H		;

	MOV	AX,ES:[BX]	;
	call	FH2A16
	MOV	AH,09H		;
	INT	21H		;

	MOV	DX,OFFSET UCDFF_M07_2
	MOV	AH,09H		;
	INT	21H		;

	inc	bx
	inc	bx

	ret			;
;---------------------------------------
;	0x09	ループ抜け
;---------------------------------------
UCDFF_M09_1	DB	'/*FE,9,$'
UCDFF_M09_2	DB	'*/:$'
UCDFF_L09:
	CMP	AL,09h		;データ終了
	JZ	UCDFF_L09_1	;
	JMP	UCDFF_L14	;
UCDFF_L09_1:
	MOV	DX,OFFSET UCDFF_M09_1
	MOV	AH,09H		;
	INT	21H		;

	mov	ah,es:[bx]
	inc	bx		;
	call	hex2asc8
	MOV	AH,09H		;
	INT	21H		;

	MOV	AX,ES:[BX]	;
	call	FH2A16
	MOV	AH,09H		;
	INT	21H		;

	MOV	DX,OFFSET UCDFF_M09_2
	MOV	AH,09H		;
	INT	21H		;

	inc	bx
	inc	bx

	ret			;
;---------------------------------------
;	0x14	音色
;---------------------------------------
UCDFF_M14_1	DB	'0a$'			;音色マクロ名
		DB	'1a$'
		DB	'2a$'
		DB	'3a$'
		DB	'4a$'
		DB	'5a$'
		DB	'6a$'
		DB	'7a$'
		DB	'0b$'
		DB	'1b$'
		DB	'2b$'
		DB	'3b$'
		DB	'4b$'
		DB	'5b$'
		DB	'6b$'
		DB	'7b$'
UCDFF_L14:
	CMP	AL,14h		;音色
	JNZ	UCDFF_L15	;
	MOV	DL,24H		;'$'の出力
	MOV	AH,02H		;
	INT	21H		;
	XOR	AX,AX		;
	MOV	AL,ES:[BX]	;
	INC	BX		;
	MOV	DX,OFFSET UCDFF_M14_1
	ADD	DX,AX		;
	ADD	DX,AX		;
	ADD	DX,AX		;
	MOV	AH,09H		;マクロ番号表示
	INT	21H		;
	RET			;
;---------------------------------------
;	0x15
;---------------------------------------
UCDFF_L15:
;	CMP	AL,15h		;不明
;	jz	UCDFF_L15_1
	Jmp	UCDFF_L16
UCDFF_L15_1:
	INC	BX		;
	INC	BX		;
	RET			;
;---------------------------------------
;	0x16
;---------------------------------------
UCDFF_L16:
;	CMP	AL,16h		;不明
;	jmp	UCDFF_L16_1	;
	JMP	UCDFF_L1C	;
UCDFF_L16_1:
	INC	BX		;
	INC	BX		;
	RET			;
;---------------------------------------
;	0x17
;---------------------------------------
UCDFF_L1C:
;	CMP	AL,1Ch		;不明
;	JZ	UCDFF_L1C_1	;
	jmp	UCDFF_LQQ
UCDFF_L1C_1:
	INC	BX		;
	INC	BX		;
	RET			;
;---------------------------------------
;	other
;---------------------------------------
UCDFF_Mst	DB	'/*FE,$'
UCDFF_Med	DB	'*/$'
UCDFF_Mc	DB	',$'
UCDFF_LQQ:

	push	ax
	MOV	DX,OFFSET UCDFF_Mst
	MOV	AH,09H		;
	INT	21H		;
	pop	ax

	mov	ah,al
	call	hex2asc8
	MOV	AH,09H		;
	INT	21H		;

	MOV	DX,OFFSET UCDFF_Mc
	MOV	AH,09H		;
	INT	21H		;

	MOV	AH,ES:[BX]	;
	INC	BX		;
	call	hex2asc8
	MOV	AH,09H		;
	INT	21H		;

	MOV	DX,OFFSET UCDFF_Mc
	MOV	AH,09H		;
	INT	21H		;

	MOV	AH,ES:[BX]	;
	INC	BX		;
	call	hex2asc8
	MOV	AH,09H		;
	INT	21H		;

	MOV	DX,OFFSET UCDFF_Med
	MOV	AH,09H		;
	INT	21H		;

	RET			;

;===============================================================
;	音色をマクロで出力する
;===============================================================
;
;		音色マクロ変換　（まだ暫定的に'@0x' を出力）
;
UC_VOICE	DB	32	DUP	(0FFh)	
UC_VOICE_NAME	DB	'0c$'			;音色マクロ名
		DB	'1c$'
		DB	'2c$'
		DB	'3c$'
		DB	'4c$'
		DB	'5c$'
		DB	'6c$'
		DB	'7c$'
		DB	'0d$'
		DB	'1d$'
		DB	'2d$'
		DB	'3d$'
		DB	'4d$'
		DB	'5d$'
		DB	'6d$'
		DB	'7d$'
		DB	'0e$'
		DB	'1e$'
		DB	'2e$'
		DB	'3e$'
		DB	'4e$'
		DB	'5e$'
		DB	'6e$'
		DB	'7e$'
		DB	'0f$'
		DB	'1f$'
		DB	'2f$'
		DB	'3f$'
		DB	'4f$'
		DB	'5f$'
		DB	'6f$'
		DB	'7f$'
UC_VOICE_OUTPUT:
	MOV	AL,ES:[BX]			;データ読み込み
	INC	BX				;
	PUSH	BX				;
	PUSH	CX				;
	PUSH	DX				;

	XOR	BX,BX				;BX←0
UC_VOICE_OUTPUT_L1:				;
	MOV	AH,CS:[UC_VOICE + BX]		;使用登録済み音色読み込み
	CMP	AH,0FFh				;登録情報終了検査
	JZ	UC_VOICE_OUTPUT_L2		;
	
	CMP	AH,AL				;音色一致検査
	JZ	UC_VOICE_OUTPUT_L3		;存在した。
	INC	BX				;
	JMP	UC_VOICE_OUTPUT_L1		;

UC_VOICE_OUTPUT_L2:				;
	MOV	CS:[UC_VOICE + BX],AL		;登録

UC_VOICE_OUTPUT_L3:				;表示
	MOV	DX,OFFSET UC_VOICE_NAME		;
	ADD	DX,BX				;
	ADD	DX,BX				;
	ADD	DX,BX				;DX←Address + BX *3
	MOV	AH,09H				;
	INT	21H				;
	JMP	UC_VOICE_OUTPUT_LE		;

UC_VOICE_OUTPUT_LE:				;終わり
	POP	DX				;
	POP	CX				;
	POP	BX				;
	RET					;

;===============================================================
;	音量とパンポット
;===============================================================
;
;		エンベロープのための記憶
;
UC_DATA_E	DB	?			;エクスプレッション
UC_DATA_P	DB	?			;パンポット

UC_SAVE_E:
	MOV	AL,ES:[BX]			;データ保存
	MOV	CS:[UC_DATA_E],AL		;
	RET					;
UC_SAVE_P:
	MOV	AL,ES:[BX]			;データ保存
	MOV	CS:[UC_DATA_P],AL		;
	RET					;
UC_LOAD_E:
	MOV	AH,ES:[BX]			;データ読み込み
	INC	BX				;
	PUSH	DX				;
	MOV	AL,CS:[UC_DATA_E]		;保存データ
	MOV	CS:[UC_DATA_E],AH		;
	SUB	AH,AL				;
	CALL	FH2A8				;出力
	MOV	AH,09H				;
	INT	21H				;
	POP	DX				;
	RET					;
UC_LOAD_P:
	MOV	AH,ES:[BX]			;データ読み込み
	INC	BX				;
	PUSH	DX				;
	MOV	AL,CS:[UC_DATA_P]		;保存データ
	MOV	CS:[UC_DATA_P],AH		;
	SUB	AH,AL				;
	CALL	FH2A8				;出力
	MOV	AH,09H				;
	INT	21H				;
	POP	DX				;
	RET					;
UC_LOAD_ES:
	PUSH	DX				;
	MOV	AH,CS:[UC_DATA_E]		;
	CALL	HEX2ASC8			;出力
	MOV	AH,09H				;
	INT	21H				;
	POP	DX				;
	RET					;
UC_LOAD_PS:
	PUSH	DX				;
	MOV	AH,CS:[UC_DATA_P]		;
	CALL	HEX2ASC8			;出力
	MOV	AH,09H				;
	INT	21H				;
	POP	DX				;
	RET					;
;===============================================================
;	音量
;===============================================================

UC_Volume_TABLE:	;指数値を、リニアに変換
			;=INT(LOG((x+1))/LOG(129)*128)
;		0	+1	+2	+3	+4	+5	+6	+7
	db	0,	18,	28,	36,	42,	47,	51,	54
	db	57,	60,	63,	65,	67,	69,	71,	73
	db	74,	76,	77,	78,	80,	81,	82,	83
	db	84,	85,	86,	87,	88,	89,	90,	91
	db	92,	92,	93,	94,	95,	95,	96,	97
	db	97,	98,	99,	99,	100,	100,	101,	101
	db	102,	103,	103,	104,	104,	105,	105,	106
	db	106,	106,	107,	107,	108,	108,	109,	109
	db	109,	110,	110,	111,	111,	111,	112,	112
	db	113,	113,	113,	114,	114,	114,	115,	115
	db	115,	116,	116,	116,	117,	117,	117,	117
	db	118,	118,	118,	119,	119,	119,	119,	120
	db	120,	120,	121,	121,	121,	121,	122,	122
	db	122,	122,	123,	123,	123,	123,	124,	124
	db	124,	124,	124,	125,	125,	125,	125,	126
	db	126,	126,	126,	126,	127,	127,	127,	127

UC_Volume:
	MOV	AL,ES:[BX]			;データ読み込み
	INC	BX				;
	PUSH	BX				;
	XOR	AH,AH				;
	MOV	BX,OFFSET UC_Volume_TABLE	;
	ADD	BX,AX				;
	MOV	AH,CS:[BX]			;
	CALL	HEX2ASC8			;出力
	MOV	AH,09H				;
	INT	21H				;
	POP	BX				;
	RET					;
;===============================================================
;	ディレイ？
;===============================================================
UC_DELAY:
	PUSH	DX				;
	MOV	AH,ES:[BX]			;データ読み込み
	INC	BX				;
;	SHR	AH,1				;AX←AX/2
	push	ax				;
	CALL	HEX2ASC8			;出力
	MOV	AH,09H				;
	INT	21H				;
	pop	ax				;
	cmp	ah,3
	jnc	UC_DELAY_1
	MOV	AH,ES:[BX]			;データ読み込み
	INC	BX				;
	CALL	HEX2ASC8			;出力
	MOV	AH,09H				;
	INT	21H				;
UC_DELAY_1:
	POP	DX				;
	RET					;
;===============================================================
;	ピッチベンド
;===============================================================
UC_Detune:
	PUSH	DX				;
	MOV	AH,ES:[BX]			;データ読み込み
	inc	bx
	add	ah,64				;
	CALL	HEX2ASC8			;出力
	MOV	AH,09H				;
	INT	21H				;
	POP	DX				;
	RET					;

